### ISSUE TITLE
Missing animation dependency?

### ISSUE THREAD

**Issue by cravecode** [xcambar/github-better-filters#3]
After building the chrome extension via `gulp dist` and attempting to load the extension into Chrome. I get the following error:

> Could not load css 'css/vendor/animate.css' for content script.

Was there something not included in the commit: a9160e48ef144b7ae9774627b8b392711e31c550

**Comment by xcambar** [comment]
Thanks for the report. You are absolutely correct. The missing file should be a release of [Animate.css](https://daneden.github.io/animate.css/).

I'll fix it later today, unless you provided a PR first ;)

**Comment by cravecode** [comment]
I hope I've gone about this the correct way, it's my first time using Gulp.

**Comment by xcambar** [comment]
Thanks a lot, that was exactly it!
